import { createDeepLinkController, updatePortalUrl } from '/js/components/deep-link-controller.js';
import { createTestSuiteApp } from '/js/apps/test-suite.js';
import { initializeActionMenus } from '/js/components/action-menu.js';
import { loadingDuckHtml } from '/js/components/loading-surfaces.js';
import { suiteSeries, suiteSegments, suiteSourceTime } from '/js/apps/test-suite-model.js';
import { mountWorkspaceFixtureShell } from '/workspace-fixture-shell.js';
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const wait = async predicate => { for (let i = 0; i < 300; i++) { if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 10)); } throw new Error('Timed out waiting for UI state'); };
const tick = () => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
const clone = value => JSON.parse(JSON.stringify(value));
const params = new URLSearchParams(location.search), mode = params.get('mode') || 'runs', scale = Number(params.get('scale') || 1);
document.documentElement.style.setProperty('--ui-font-scale', scale); document.documentElement.style.setProperty('--ui-component-scale', scale);
const host = document.getElementById('runtimeFixtureRoot'); host.innerHTML = '<section id="test-suite" class="app active"><div id="testSuiteRoot" class="ui-render-root ui-workspace"></div></section>';
initializeActionMenus();
window.App = mountWorkspaceFixtureShell({ state: {}, app: 'test-suite', root: document.getElementById('testSuiteRoot') });
const sourceSettings = { jvmTargetId: 4, browserConfigurationId: 34, initialUrl: 'https://shop.harbor.example.invalid/checkout', resetOrigins: ['https://shop.harbor.example.invalid'], sampleIntervalMillis: 1000, jfrEnabled: true, browserOptions: { mode: 'ALL_TABS', captureHtml: false, captureNetworkPayloads: false, attemptRedaction: true } };
let folders = [{ id: 1, parentId: null, name: 'Harbor Commerce', revision: 0 }, { id: 2, parentId: 1, name: 'Checkout / delivery sorting', revision: 0 }, { id: 3, parentId: null, name: 'Catalogue exploration', revision: 0 }];
let profiles = [{ id: 1, folderId: 2, name: 'Delivery options · Browser + JVM', alias: 'Harbor#delivery-sort', description: 'Capture navigation and checkout interactions alongside service resource measurements.', settings: clone(sourceSettings), revision: 3, updatedAt: '2026-09-29T09:00:00Z', archived: false }, { id: 2, folderId: 2, name: 'Returning customer · saved address', alias: 'Harbor#returning-customer', description: '', settings: clone(sourceSettings), revision: 1 }, { id: 3, folderId: 3, name: 'Catalog browsing', alias: 'Harbor#catalogue', description: '', settings: clone(sourceSettings), revision: 1 }];
const origin = '2026-09-29T09:00:00Z', at = ms => new Date(Date.parse(origin) + ms).toISOString();
const makeRun = (id, multiplier = 1) => ({ id, profileId: 1, requestId: `fixture-${id}`, state: 'COMPLETED', phase: 'Capture stopped; browser remains open', profile: clone(profiles[0]), metadata: { revision: `delivery-sort-${id}`, applicationVersion: '2.4.0', dataset: '2,000 fictional delivery options', note: 'Delivery sort interaction' }, createdAt: origin, startedAt: at(2000), finishedAt: at(62000), revision: 1, readyForInteraction: false, browserSessionId: 'harbor-demo-browser-01', sources: [{ source: 'JVM', groupId: id * 10, recordingIds: [id * 10], state: 'COMPLETED' }, { source: 'BROWSER', groupId: id * 10 + 1, recordingIds: [id * 10 + 1], state: 'COMPLETED', sessionId: 'harbor-demo-browser-01' }], markers: [{ id: 'capture', name: 'All sources capturing', capturedAt: at(2000), clockBasis: 'WORKBENCH_MONOTONIC', uncertaintyMillis: 0 }, { id: 'navigation', name: 'Initial navigation requested', capturedAt: at(4000), source: 'BROWSER', clockBasis: 'WORKBENCH_OBSERVED', uncertaintyMillis: 3 }], annotations: [{ id: 'note-1', text: 'Submitted checkout form', offsetMillis: 28000, createdAt: at(28000), author: 'developer' }], environment: { browser: { name: 'Brave', version: '138', operatingSystem: 'Windows', viewport: '1440 × 900' }, jvm: { name: 'harbor-checkout-service', javaVersion: '22', processors: 8, maxHeap: '2 GiB', operatingSystem: 'Linux' }, clockNote: 'Capture clocks are recorded independently.' }, warnings: [], portalUrl: `/?app=test-suite&runId=${id}`, multiplier });
profiles.push({ ...clone(profiles[0]), id: 4, folderId: 3, name: 'Search results · 2,000 products', alias: 'Harbor#search', revision: 2 }, { ...clone(profiles[0]), id: 5, folderId: 2, name: 'Pickup point selection', alias: 'Harbor#pickup', revision: 1 });
let delayedProfile = null, releaseProfile, rejectSave = false;
let runs = [makeRun(108, .86), makeRun(107, .93), makeRun(106, 1.04), makeRun(105, .96), makeRun(104, 1.02), makeRun(103, 1.08), makeRun(102, 1), makeRun(101, 1.1)], writes = [], confirmation = true, failNextRead = false, nextRun = 103;
const windowResult = (id, source) => { const run = runs.find(item => item.id === id) || makeRun(id), jvm = source === 'JVM', anchor = jvm ? 738194000 : 0, clock = { sourceAnchorMillis: anchor, utcAnchor: at(2000), uncertaintyMillis: jvm ? 0 : 3, clockBasis: jvm ? 'WORKBENCH_MONOTONIC' : 'WORKBENCH_OBSERVED' }; const buckets = Array.from({ length: 60 }, (_, i) => ({ fromMillis: anchor + i * 1000, toMillis: anchor + (i + 1) * 1000, missing: i >= 20 && i <= 22, metrics: jvm ? { processCpuPercent: { mean: (15 + Math.sin(i / 4) * 8 + (i > 26 && i < 36 ? 35 : 0)) * run.multiplier }, heapUsedBytes: { mean: (280 + i * 3 - (i > 40 ? 80 : 0)) * 1048576 * run.multiplier }, platformThreadCount: { mean: 38 + Math.round(Math.sin(i / 5) * 6) } } : { taskBusyPercent: { mean: (8 + Math.cos(i / 4) * 6 + (i > 26 && i < 36 ? 45 : 0)) * run.multiplier }, jsHeapUsedBytes: { mean: (90 + i * 1.1) * 1048576 * run.multiplier }, nodes: { mean: 830 + i * 20 } } })); return { source, clock, runOrigin: run.createdAt, recordings: [{ recordingId: id * 10 + (jvm ? 0 : 1), name: jvm ? 'harbor-checkout-service' : 'Harbor checkout', contextId: jvm ? 'jvm:4' : 'tab-1', state: 'COMPLETED', clock, overview: { buckets }, events: [], nextSequence: 200, hasMore: true }], warnings: [] }; };
const api = async (method, path, body) => {
	const url = new URL(path, 'http://fixture'), part = url.pathname;
	if (method !== 'GET') writes.push({ method, path, body: clone(body || {}) });
	if (method === 'GET' && failNextRead) { failNextRead = false; throw new Error('Fixture temporary connection failure'); }
	if (part === '/api/browsers/configurations') return [{ id: 34, name: 'Brave · dedicated test browser', browserType: 'BRAVE', enabled: true }, { id: 65, name: 'Chrome', browserType: 'CHROME', enabled: true }, { id: 33, name: 'Firefox', browserType: 'FIREFOX', enabled: true }];
	if (part === '/api/performance-runs/jvm/targets') return [{ id: 4, name: 'Harbor checkout service · local Java 22', granted: true, enabled: true }, { id: 5, name: 'inventory-service · awaiting approval', granted: false, enabled: true }];
	if (part === '/api/test-suite/folders') { if (method === 'GET') return clone(folders); const result = { ...body, id: 8, revision: 0 }; folders.push(result); return clone(result); }
	if (/\/folders\/\d+$/.test(part)) { const id = Number(part.split('/').at(-1)); if (method === 'DELETE') { folders = folders.filter(item => item.id !== id); return {}; } folders = folders.map(item => item.id === id ? { ...item, ...body, revision: item.revision + 1 } : item); return clone(folders.find(item => item.id === id)); }
	if (part === '/api/test-suite/profiles') { if (method === 'GET') return { items: clone(profiles), page: 0, limit: 200, hasMore: false }; const result = { ...body, id: 10, revision: 0 }; profiles.push(result); return clone(result); }
	if (part.endsWith('/readiness')) return [{ source: 'BROWSER', ready: true, message: 'Saved browser configuration and origins are permitted.' }, { source: 'JVM', ready: true, message: 'Owned target is enabled and approved. Connection occurs only on Start.' }];
	if (/\/profiles\/\d+$/.test(part)) { const id = Number(part.split('/').at(-1)); if (method === 'GET') { if (delayedProfile === id) { delayedProfile = null; await new Promise(resolve => releaseProfile = resolve); } return clone(profiles.find(item => item.id === id)); } if (rejectSave) { rejectSave = false; throw new Error('Profile revision changed. Reload before saving.'); } if (method === 'DELETE') { profiles = profiles.filter(item => item.id !== id); return {}; } profiles = profiles.map(item => item.id === id ? { ...item, ...body, revision: item.revision + 1 } : item); return clone(profiles.find(item => item.id === id)); }
	if (part === '/api/test-suite/runs') { if (method === 'GET') return { items: clone(runs), page: Number(url.searchParams.get('page') || 0), limit: 50, hasMore: false }; const result = { ...makeRun(nextRun++), state: 'PREPARING', phase: 'Connecting existing JVM', finishedAt: null, readyForInteraction: false }; runs.unshift(result); return clone(result); }
	if (part.endsWith('/window')) return windowResult(Number(part.split('/').at(-2)), url.searchParams.get('source'));
	if (part.endsWith('/close-browser')) return { closed: true };
	if (part.endsWith('/stop')) { const item = runs.find(run => run.id === Number(part.split('/').at(-2))); Object.assign(item, { state: 'COMPLETED', phase: 'Capture stopped; browser remains open', finishedAt: at(62000), readyForInteraction: false }); return clone(item); }
	if (part.endsWith('/annotations')) { const item = runs.find(run => run.id === Number(part.split('/').at(-2))); item.annotations.push({ ...body, id: 'added', createdAt: at(body.offsetMillis), author: 'developer' }); return clone(item); }
	if (/\/runs\/\d+$/.test(part)) { const id = Number(part.split('/').at(-1)); if (method === 'DELETE') { runs = runs.filter(item => item.id !== id); return {}; } return clone(runs.find(item => item.id === id)); }
	throw new Error(`Unexpected fixture request ${method} ${path}`);
};
if (mode === 'empty') { folders = []; profiles = []; runs = []; }
const app = createTestSuiteApp({ api, loadingDuckHtml, confirmDialog: async () => confirmation, updatePortalUrl: () => {}, alertBox: (id, ok, message) => { const element = document.getElementById(id); element.hidden = false; element.textContent = message; } });
window.testSuiteFixtureApp = app;
const click = async selector => { const element = document.querySelector(selector); assert(element, `Missing ${selector}`); element.click(); await tick(); };
const input = (id, value) => { const element = document.getElementById(id); element.value = value; element.dispatchEvent(new Event('input', { bubbles: true })); };

await app.load(); await app.openLocation({ profileId: 1, runId: 108, view: 'runs', compare: '102', align: 'navigation' });
await wait(() => document.querySelectorAll('.ts-series').length > 5);
document.getElementById('tsHistory').open = false; document.activeElement?.blur(); await tick(); window.suiteReady=true;
